### ISSUE TITLE
Problem with the Google icon in ConnectKit

### ISSUE THREAD

**Issue by JulioMCruz** [zerodevapp/zerodev-wagmi#14]
In src/Integrations/ConnectKit/supportedSocialConnectors.tsx, the Google icon does not exist anymore, 
In the code is this one:
https://upload.wikimedia.org/wikipedia/commons/thu…2G%22_Logo.svg/2048px-Google_%22G%22_Logo.svg.png

we can use the following one
https://cdn1.iconfinder.com/data/icons/logos-brands-in-colors/544/Google__G__Logo-1024.png

Thank You

**Comment by blakecduncan** [comment]
Fixed here!
https://github.com/zerodevapp/zerodev-wagmi/commit/2d3913cdcdfa1d92b3e6f805a3c8a05912252b12
